; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f
; Function compile flags: /Odtp
_TEXT	SEGMENT
f	PROC
; File d:\Reverse\1.re4b\re4b\1.chapter\1.4\returnVal.c
; Line 16
	mov	eax, 123				; 0000007bH
; Line 17
	ret	0
f	ENDP
_TEXT	ENDS
END
