; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

	TITLE	D:\Reverse\1.re4b\re4b\1.chapter\1.3\emptyFun.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f	PROC
; File D:\Reverse\1.re4b\re4b\1.chapter\1.3\emptyFun.c
; Line 14
	push	ebp
	mov	ebp, esp
; Line 16
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
END
